name = "nceahelpworker"
main = "./src/server.ts"
compatibility_date="2024-09-12"

account_id= "4ed1f8e12cda519236361f09dd8956cf"
send_metrics = true
minify = true

route = { pattern = "discord.worker.nceahelp.com", zone_name = "nceahelp.com", custom_domain = true }

kv_namespaces = [
  { binding = "TOKEN_STORE", id = "6054fb4ce09045aea65372b682e4fdbf"}
]

tail_consumers = [{service = "nceahelpworker-tail"}]

[placement]
mode = "smart"

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
