name: "Register to Discord"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/commands.js'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Run registration
        run: |
          export DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
          export DISCORD_APPLICATION_ID=${{ secrets.DISCORD_APPLICATION_ID }}
          pnpm run register
